In [1]:
import re
import pandas as pd
import numpy as np


In [2]:
dataset = pd.read_csv('reviews.csv') #To read Datasets
#dataset = dataset.head(5000)
dataset

asin               name  rating                date  verified  \
0      B0000SX2UC              Janet       3    October 11, 2005     False   
1      B0000SX2UC         Luke Wyatt       1     January 7, 2004     False   
2      B0000SX2UC             Brooke       5   December 30, 2003     False   
3      B0000SX2UC      amy m. teague       3      March 18, 2004     False   
4      B0000SX2UC      tristazbimmer       4     August 28, 2005     False   
...           ...                ...     ...                 ...       ...   
67981  B081H6STQQ              jande       5     August 16, 2019     False   
67982  B081H6STQQ            2cool4u       5  September 14, 2019     False   
67983  B081H6STQQ              simon       5       July 14, 2019     False   
67984  B081TJFVCJ  Tobiasz Jedrysiak       5   December 24, 2019      True   
67985  B0825BB7SG      Owen Gonzalez       5   December 11, 2019     False   

                                                   title  \
0                            Def not best, but not worst   
1                            Text Messaging Doesn't Work   
2                                        Love This Phone   
3                                Love the Phone, BUT...!   
4           Great phone service and options, lousy case!   
...                                                  ...   
67981  Awesome Phone, but finger scanner is a big mis...   
67982                                    Simply Amazing!   
67983  great phon3, but many bugs need to fix. still ...   
67984                                  Phone is like new   
67985                    Outstanding phone for the price   

                                                    body  helpfulVotes  
0      I had the Samsung A600 for awhile which is abs...           1.0  
1      Due to a software issue between Nokia and Spri...          17.0  
2      This is a great, reliable phone. I also purcha...           5.0  
3      I love the phone and all, because I really did...           1.0  
4      The phone has been great for every purpose it ...           1.0  
...                                                  ...           ...  
67981  I love the camera on this phone. The screen is...           1.0  
67982  I've been an Xperia user for several years and...           1.0  
67983                         buy one more for my cousin           NaN  
67984  Product looks and works like new. Very much re...           NaN  
67985  I love the size and style of this phone. It is...           NaN  

[67986 rows x 8 columns]

In [3]:
dataset.isnull().sum() #To check the number of NULL values on each columns

asin                0
name                2
rating              0
date                0
verified            0
title              14
body               21
helpfulVotes    40771
dtype: int64

In [4]:
dataset['body'] = dataset['body'].fillna('').apply(str)
dataset['name'] = dataset['name'].fillna('').apply(str)
dataset['title'] = dataset['title'].fillna('').apply(str)
dataset['helpfulVotes'] = dataset['helpfulVotes'].fillna('').apply(str)     #To fill the mentioned columns' NULL value 


In [5]:
dataset.isnull().sum()  # To check the number of NULL values on each columns to make sure there are no more NULL values


asin            0
name            0
rating          0
date            0
verified        0
title           0
body            0
helpfulVotes    0
dtype: int64

In [6]:
dataset = dataset.drop(columns = ['asin', 'name', 'helpfulVotes', 'date'], axis = 1)    #To remove columns

In [7]:
a = dataset['rating'].tolist()  # to store the rating values in a list
a


[3,
 1,
 5,
 3,
 4,
 4,
 5,
 4,
 5,
 3,
 4,
 1,
 2,
 4,
 1,
 4,
 5,
 1,
 5,
 1,
 5,
 4,
 1,
 1,
 5,
 3,
 4,
 1,
 5,
 3,
 1,
 5,
 5,
 5,
 5,
 4,
 4,
 5,
 5,
 4,
 4,
 3,
 4,
 4,
 1,
 5,
 5,
 1,
 5,
 4,
 1,
 5,
 5,
 1,
 4,
 1,
 5,
 5,
 5,
 1,
 1,
 5,
 1,
 5,
 4,
 5,
 3,
 5,
 3,
 5,
 5,
 2,
 3,
 1,
 5,
 4,
 3,
 1,
 4,
 1,
 3,
 4,
 3,
 2,
 4,
 3,
 4,
 3,
 2,
 5,
 2,
 5,
 1,
 4,
 3,
 4,
 1,
 5,
 5,
 5,
 3,
 4,
 2,
 3,
 4,
 1,
 5,
 1,
 1,
 2,
 4,
 5,
 1,
 5,
 1,
 5,
 3,
 4,
 5,
 3,
 2,
 1,
 3,
 5,
 5,
 2,
 3,
 5,
 1,
 1,
 4,
 5,
 3,
 5,
 2,
 1,
 3,
 3,
 5,
 1,
 1,
 5,
 1,
 1,
 5,
 5,
 3,
 4,
 3,
 3,
 1,
 5,
 5,
 1,
 1,
 2,
 4,
 1,
 1,
 1,
 1,
 1,
 4,
 1,
 1,
 5,
 2,
 4,
 5,
 1,
 4,
 5,
 5,
 3,
 1,
 5,
 5,
 5,
 5,
 1,
 2,
 5,
 1,
 5,
 1,
 3,
 1,
 1,
 3,
 5,
 4,
 2,
 1,
 1,
 2,
 1,
 1,
 1,
 4,
 1,
 5,
 2,
 1,
 5,
 5,
 5,
 1,
 1,
 5,
 1,
 5,
 3,
 5,
 1,
 5,
 1,
 4,
 4,
 1,
 3,
 1,
 5,
 1,
 5,
 5,
 4,
 1,
 1,
 2,
 1,
 5,
 1,
 3,
 1,
 1,
 1,
 5,
 5,
 5,
 2,
 5,
 2,
 1,
 1,
 1,
 3,
 1,
 1,
 1,
 5,


In [8]:
d = []

#Assign 1 to the ratings above 3 or else assign 0
for i in range(len(a)):
    if a[i]>=3:
        d.append(1)
    else:
        d.append(0)

d


[1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,


In [9]:
dt = pd.DataFrame(d, columns = ['emotion'])     #Set the list as an emoticon column
dt

emotion
0            1
1            0
2            1
3            1
4            1
...        ...
67981        1
67982        1
67983        1
67984        1
67985        1

[67986 rows x 1 columns]

In [10]:
data1 = pd.concat([dataset,dt], axis = 1)   #To concat the emotion column with the dataset
data1

rating  verified                                              title  \
0           3     False                        Def not best, but not worst   
1           1     False                        Text Messaging Doesn't Work   
2           5     False                                    Love This Phone   
3           3     False                            Love the Phone, BUT...!   
4           4     False       Great phone service and options, lousy case!   
...       ...       ...                                                ...   
67981       5     False  Awesome Phone, but finger scanner is a big mis...   
67982       5     False                                    Simply Amazing!   
67983       5     False  great phon3, but many bugs need to fix. still ...   
67984       5      True                                  Phone is like new   
67985       5     False                    Outstanding phone for the price   

                                                    body  emotion  
0      I had the Samsung A600 for awhile which is abs...        1  
1      Due to a software issue between Nokia and Spri...        0  
2      This is a great, reliable phone. I also purcha...        1  
3      I love the phone and all, because I really did...        1  
4      The phone has been great for every purpose it ...        1  
...                                                  ...      ...  
67981  I love the camera on this phone. The screen is...        1  
67982  I've been an Xperia user for several years and...        1  
67983                         buy one more for my cousin        1  
67984  Product looks and works like new. Very much re...        1  
67985  I love the size and style of this phone. It is...        1  

[67986 rows x 5 columns]

In [11]:
data1.shape     #Check the data1 shape


(67986, 5)

In [12]:
# dropping a verified column from data1
data1.drop(['verified'], axis=1, inplace=True)


In [13]:
#Joining the title and body as a review
data1['Review'] = data1[['title', 'body']].agg(' '.join, axis=1) 


In [14]:
#dropping the remaining columns title, body, and rating from data1.
data1.drop(['title','body','rating'], axis=1, inplace=True)


In [15]:
data1

emotion                                             Review
0            1  Def not best, but not worst I had the Samsung ...
1            0  Text Messaging Doesn't Work Due to a software ...
2            1  Love This Phone This is a great, reliable phon...
3            1  Love the Phone, BUT...! I love the phone and a...
4            1  Great phone service and options, lousy case! T...
...        ...                                                ...
67981        1  Awesome Phone, but finger scanner is a big mis...
67982        1  Simply Amazing! I've been an Xperia user for s...
67983        1  great phon3, but many bugs need to fix. still ...
67984        1  Phone is like new Product looks and works like...
67985        1  Outstanding phone for the price I love the siz...

[67986 rows x 2 columns]

In [16]:
#Check data1 shape
data1.shape

(67986, 2)

In [17]:
x = data1.iloc[:,1].values  #input (Review)
y = data1.iloc[:,0].values  #output (emotion, 1 or 0)


In [18]:
#import natural language toolkit
import nltk
#import stopwords library to remove stopword
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
#Library imported to stem the words
from nltk.stem.porter import PorterStemmer
#Object for stemming
ps = PorterStemmer()

#import object for wordnet Lemmatizer
from nltk.stem import WordNetLemmatizer
wordnet = WordNetLemmatizer()

corpus = []


In [19]:
for i in range(0, len(x)):
    temp = data1['Review'][i] #Set temp as the i row of review
    temp = re.sub('[^a-zA-Z]', ' ', temp)   #replace punctuation and number with re Library
    temp = re.sub(r'\d+', ' ', temp)
    temp = temp.replace('[^\W\s\S]', ' ')
    temp = temp.lower().split() #Convert text to lower cases and then split to array
    temp = [ps.stem(word) for word in temp if not word in set(stopwords.words('english'))]   #Loop to stemmatize each word in string array
    temp = ' '.join(temp)   #Rejoin all string array into a single string
    corpus.append(temp) #append each string to create array of clean text
    if i % 100 == 0:
        print(str(i) + " out of " + str(len(x)) + " Completed !!")  #Show which rows is done
        if i == len(x):
            print(str(len(x)) + " out of " + str(len(x)) + " Completed !!")


0 out of 67986 Completed !!
100 out of 67986 Completed !!
200 out of 67986 Completed !!
300 out of 67986 Completed !!
400 out of 67986 Completed !!
500 out of 67986 Completed !!
600 out of 67986 Completed !!
700 out of 67986 Completed !!
800 out of 67986 Completed !!
900 out of 67986 Completed !!
1000 out of 67986 Completed !!
1100 out of 67986 Completed !!
1200 out of 67986 Completed !!
1300 out of 67986 Completed !!
1400 out of 67986 Completed !!
1500 out of 67986 Completed !!
1600 out of 67986 Completed !!
1700 out of 67986 Completed !!
1800 out of 67986 Completed !!
1900 out of 67986 Completed !!
2000 out of 67986 Completed !!
2100 out of 67986 Completed !!
2200 out of 67986 Completed !!
2300 out of 67986 Completed !!
2400 out of 67986 Completed !!
2500 out of 67986 Completed !!
2600 out of 67986 Completed !!
2700 out of 67986 Completed !!
2800 out of 67986 Completed !!
2900 out of 67986 Completed !!
3000 out of 67986 Completed !!
3100 out of 67986 Completed !!
3200 out of 67986 Co

In [20]:
#Create bag of word model
from sklearn.feature_extraction.text import CountVectorizer
#Extract 2000 max feture, which is the attribute to experiment with to get better result
cv = CountVectorizer(max_features = 2000)
#z contains vectorized data
z = cv.fit_transform(corpus).toarray()


In [21]:
import pickle
#Save the Bag of word model
pickle.dump(cv, open('count_vec.pkl', 'wb'))


In [22]:
#Contains vectorized data
x = cv.fit_transform(corpus).toarray()

In [46]:
x

array([[0, 0, 1, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [24]:
y

array([1, 0, 1, ..., 1, 1, 1], dtype=int64)

In [25]:
from sklearn.model_selection import train_test_split
#Splitting the data to train and test set
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state = 0)


In [26]:
x_train.shape #Show x train shape

(54388, 2000)

In [27]:
x_test.shape #show x test shape

(13598, 2000)

In [28]:
y_test.shape #show y test shape

(13598,)

In [29]:
data1   #Show data1 table

emotion                                             Review
0            1  Def not best, but not worst I had the Samsung ...
1            0  Text Messaging Doesn't Work Due to a software ...
2            1  Love This Phone This is a great, reliable phon...
3            1  Love the Phone, BUT...! I love the phone and a...
4            1  Great phone service and options, lousy case! T...
...        ...                                                ...
67981        1  Awesome Phone, but finger scanner is a big mis...
67982        1  Simply Amazing! I've been an Xperia user for s...
67983        1  great phon3, but many bugs need to fix. still ...
67984        1  Phone is like new Product looks and works like...
67985        1  Outstanding phone for the price I love the siz...

[67986 rows x 2 columns]

In [30]:
#Setting the neuron layers
#The classification is in categoritical
import tensorflow
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential()
model.add(Dense(2000, activation='relu'))
model.add(Dense(4000, activation='relu'))
model.add(Dense(4000, activation='relu'))
model.add(Dense(4000, activation='relu'))
model.add(Dense(1, activation='sigmoid'))
model.compile(optimizer='adam', loss='binary_crossentropy', metrics = ['accuracy'])
model.fit(x_train, y_train, batch_size = 128, epochs=15)



Epoch 1/15
425/425 [==============================] - 225s 518ms/step - loss: 0.2497 - accuracy: 0.8982
Epoch 2/15
425/425 [==============================] - 228s 537ms/step - loss: 0.1430 - accuracy: 0.9427
Epoch 3/15
425/425 [==============================] - 229s 538ms/step - loss: 0.0709 - accuracy: 0.9747
Epoch 4/15
425/425 [==============================] - 228s 535ms/step - loss: 0.0337 - accuracy: 0.9890
Epoch 5/15
425/425 [==============================] - 227s 533ms/step - loss: 0.0234 - accuracy: 0.9925
Epoch 6/15
425/425 [==============================] - 227s 533ms/step - loss: 0.0163 - accuracy: 0.9943
Epoch 7/15
425/425 [==============================] - 228s 536ms/step - loss: 0.0178 - accuracy: 0.9948
Epoch 8/15
425/425 [==============================] - 226s 533ms/step - loss: 0.0133 - accuracy: 0.9960
Epoch 9/15
425/425 [==============================] - 212s 500ms/step - loss: 0.0112 - accuracy: 0.9967
Epoch 10/15
425/425 [==============================] - 212s 498m

In [31]:
model.summary() #Show the model network

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 2000)              4002000   
_________________________________________________________________
dense_1 (Dense)              (None, 4000)              8004000   
_________________________________________________________________
dense_2 (Dense)              (None, 4000)              16004000  
_________________________________________________________________
dense_3 (Dense)              (None, 4000)              16004000  
_________________________________________________________________
dense_4 (Dense)              (None, 1)                 4001      
Total params: 44,018,001
Trainable params: 44,018,001
Non-trainable params: 0
_________________________________________________________________


In [32]:
model.save('review.h5') #Save the model in h5 file


In [33]:
#Test for the model part 1
text = "The product is bad"
text = re.sub('[^a-zA-Z]', ' ', text)
text = text.lower().split()
text = [ps.stem(word) for word in text if not word in set(stopwords.words('english'))]
text = ' '.join(text)


In [34]:
y_p1 = model.predict(cv.transform([text]))

y_p1

array([[0.00095823]], dtype=float32)

In [35]:
y_p1 = y_p1 > 0.5
y_p1

array([[False]])

In [36]:
text

'product bad'

In [37]:
#Test for the model part 2
text2 = "Product good"
text2 = re.sub('[^a-zA-Z]', ' ', text2)
text2 = text2.lower().split()
text2 = [ps.stem(word) for word in text2 if not word in set(stopwords.words('english'))]
text2 = ' '.join(text2)


In [38]:
y_p2 = model.predict(cv.transform([text2]))
y_p2

array([[0.9994168]], dtype=float32)

In [39]:
text2

'product good'

In [44]:
#Test for the model part 3
text3 = "Bad"
text3 = re.sub('[^a-zA-Z]', ' ', text3)   #replace punctuation and number with re Library
text3 = re.sub(r'\d+', ' ', text3)
text3 = text3.replace('[^\W\s\S]', ' ')
text3 = text3.lower().split()
text3 = [ps.stem(word)
         for word in text3 if not word in set(stopwords.words('english'))]
text3 = ' '.join(text3)


In [45]:
y_p3 = model.predict(cv.transform([text3]))
y_p3


array([[0.55861425]], dtype=float32)